GET http://localhost:5093/games

###
GET http://localhost:5093/games/1

###
POST http://localhost:5093/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genre": "Kids and Family",
  "price": 19.99,
  "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5093/games/1
Content-Type: application/json

{
  "name": "Civilization VI (Sale)",
  "genre": "4X",
  "price": 29.99,
  "releaseDate": "2016-10-21"
}

###
DELETE http://localhost:5093/games/2