GET http://localhost:5093/games

###
GET http://localhost:5093/games/1

###
POST http://localhost:5093/games
Content-Type: application/json

{
  "name": "Civilization VI",
  "genreId": 1,
  "price": 59.99,
  "releaseDate": "2016-10-21"
}

###
PUT http://localhost:5093/games/4
Content-Type: application/json

{
  "name": "Civilization VI (Sale)",
  "genreId": 1,
  "price": 29.99,
  "releaseDate": "2016-10-21"
}

###
DELETE http://localhost:5093/games/2